### ISSUE TITLE
Make a release!

### ISSUE THREAD

**Issue by MrMysterius** [sempostma/cc0-file-icons#1]
Simply make a release where you add a compressed archive (zip, etc.) with the icons. It's and easy to find download on GitHub.

![image](https://user-images.githubusercontent.com/25854814/130780646-dcf11004-966e-4240-9264-4a9c4bbc53ce.png)

**Comment by sempostma** [comment]
Here you go: https://github.com/sempostma/cc0-file-icons/releases/tag/1.0.0

**Comment by MrMysterius** [comment]
👍

**Comment by MrMysterius** [comment]
👍
